-- 添加缺失的 status 列
ALTER TABLE IF EXISTS students ADD COLUMN IF NOT EXISTS status VARCHAR(20) DEFAULT '正常';
ALTER TABLE IF EXISTS attendance ADD COLUMN IF NOT EXISTS status VARCHAR(20) NOT NULL DEFAULT 'present';
ALTER TABLE IF EXISTS fee_item ADD COLUMN IF NOT EXISTS status VARCHAR(20) DEFAULT 'active';
ALTER TABLE IF EXISTS fee_record ADD COLUMN IF NOT EXISTS status VARCHAR(20) DEFAULT 'unpaid';
ALTER TABLE IF EXISTS pickup_record ADD COLUMN IF NOT EXISTS status VARCHAR(20) DEFAULT 'normal';
ALTER TABLE IF EXISTS users ADD COLUMN IF NOT EXISTS status VARCHAR(20) DEFAULT 'pending';